services:

  #Frontend service
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: daria-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    #cmmand: npx vite --host 0.0.0.0 --port 3000    
    
    # depends_on:
    #   - backend

  # #Backend service
  # backend:
  #   build: ./backend
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./backend:/app
  #   command: uvicorn main:app --host
