# docker-compose
services:

  #Frontend service
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: daria-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    #cmmand: npx vite --host 0.0.0.0 --port 3000    
    
    # depends_on:
    #   - backend

  # THE REDIS STORAGE 
  redis-store:
    image: redis:7.4-alpine
    container_name: redis_storage
    ports:
      - "6379:6379"
    # Essential for persistent data testing
    volumes:
      - redis_data:/data

  # NODE BACKEND
  backend:
    build:
      context: ./backend      # Look in the backend folder
      dockerfile: Dockerfile  # Use your Multi-Stage Dockerfile
    container_name: daria-backend
    image: daria-backend
    volumes:
      - ./backend:/app    # tells docker to 'stream' code from /backend
      - /app/node_modules # tells docker to use the node_modules built by the container
      - ./.gcloud_config/application_default_credentials.json:/app/.gcloud_config/credentials.json:ro # injects the crendential (was ignored before)
    environment:
    - APP_ENV=development
    - GOOGLE_APPLICATION_CREDENTIALS=/app/.gcloud_config/credentials.json # Overrides the env path, which is dev-specific
    depends_on:
      - redis-store
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
  
volumes:
  redis_data: